version: '3.9'

services:
  frontend:
    build: 
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0

  backend:
    build: 
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app
    env_file:
      - .env
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload